### ISSUE TITLE
Vue Redux + Vue Router

### ISSUE THREAD

**Issue by BosNaufal** [yang-wei/vue-flux#23]
Hey @yang-wei, It's a great plugin :grin: :+1: 

But, how can I use it with vue router? Is there any docs that I missed to read? :confused:

**Comment by yang-wei** [comment]
it shows a simple example rather than a complete plugin.

If you want to manage your app state you should wrap your app with vue router with redux.
I never try this before but as long as your app is working with vue router you can wrap them using this plugin to manage your application state

**Comment by BosNaufal** [comment]
Thanks @yang-wei! :grin: :+1:
