### ISSUE TITLE
Use Redux 1.0 RC

### ISSUE THREAD

**Issue by gaearon** [yang-wei/vue-flux#4]
Redux 1.0 RC contains breaking changes from 0.12, but its API is stable.
Please use it instead.

1.0 RC API reference: https://github.com/gaearon/redux/blob/rewrite-docs/docs/Reference/API.md
Breaking changes: https://github.com/gaearon/redux/releases/tag/v1.0.0-rc

**Comment by yang-wei** [comment]
:+1:

**Comment by gaearon** [comment]
Thanks! I understand the README needs a small update, too?

**Comment by yang-wei** [comment]
> Thanks! I understand the README needs a small update, too?

True. Done !
